using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SobreCadaUm : MonoBehaviour
{
    /*
        DISTANCE JOINT: - FUNCIONA COMO PÊNDULO, FICA BALANÇANDO DE UM LADO PARA OUTRO COMO SE FOSSE PRESO À UMA CORDA

        FIXED JOINT:    - FUNCIONA COMO UM TRÂMPOLIM E TAMBÉM PODE SER UTILIZADO PARA FAZER PONTES QUE SE 
                        BALANÇAM OU PODEM QUEBRAR CONFORME A FORÇA DO PERSONAGEM

        FRICTION JOINT: - PODE FUNCIONAR DE DUAS FORMAS:
                            1º PODE SER UM "BOTÃO" QUE CONFORME VOCÊ PULA EM CIMA ELE VAI DESCENDO.
                            2º PODE FUNCIONAR COMO UMA PLATAFORMA FRACA QUE GIRA QUE, CONFORME VOCÊ CHEGA ÀS EXTREMIDADES
                            ELA PODE VIRAR E O PERSONAGEM CAIR

        HINGE JOINT:    - MUITO UTILIZADO PARA CRIAR EFEITO DE CORDAS SUSPENSAS E TAMBÉM PODE SER UTILIZADO COMO PLATAFORMA FRACA COM MOTOR
                        QUE AO PERSONAGEM CHEGAR NA EXTREMIDADE ELA PERDE SUA FORÇA
        
        RELATIVE JOINT: - FUNCIONA COMO UMA PLATAFORMA QUE AO PULAR EM CIMA, ELA DESCE UM POUCO E RETORNA AO SEU LUGAR

        SLIDER JOINT:   - FUNCIONA COMO UMA PLATAFORMA QUE VAI DE UM LADO PARA OUTRO

        SPRING JOINT:   - FUNCIONA COMO UMA MOLA

        TARGET JOINT:   - FUNCIONA TAMBÉM COMO MOLA, PORÉM NÃO SE FIXA A NENHUM OBJETO.

        WHEEL JOINT:    - ROTACIONA AO REDOR DE UM EIXO, MUITO UTILIZADO PARA FAZER CARROS SE MOVIMENTAREM
    */
}
