using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SobreCadaUm : MonoBehaviour
{
    /*
        AREA EFFECTOR:      - COLOCA UMA FORÇA EM UMA DETERMINADA DIREÇÃO, DENTRO DE UMA ÁREA.
                            PODE SER USADO PARA CRIAR VENTOS OU PLATAFORMAS MÓVEIS (ESTEIRA) E TAMBÉM COMO VAPOR QUE FORÇA IR PARA CIMA

        BUOYANCY EFFECTOR:  - POSSUI PROPRIEDADES PARA CRIAR EFEITOS DE ÁGUA (BOIAR, AFUNDAR, CORRENTEZA, ETC)

        POINT EFFECTOR:     - SERVE PARA CRIAR EXPLOSÕES E EFEITOS DE IMÃ

        PLATAFORM EFFECTOR: - SERVE PARA CRIAR OS EFEITOS DE:
                                1º - ATRAVESSAR PLATAFORMAS POR BAIXO
                                2º - CRIAR FRICÇÃO EM RAMPAS
                                3º - CRIAR PULA PULA

        SURFACE EFFECTOR:   - SERVE PARA CRIAR EFEITOS DE ESTEIRA EM PLATAFORMAS

        CONSTANT FORCE:     - SERVE PARA CRIAR ELEMENTOS QUE FICAM SEMPRE ROTACIONANDO OU QUE IRÃO SE MOVIMENTAR EM DIVERSOS EIXOS.        
    */
}
